---
- name: setup docker on all hosts
  hosts: docker
  roles:
    - { role: ansible-roles/install-docker, docker_user: ubuntu }

- name: start jenkins docker, configure jenkins
  hosts: jenkins
  roles:
    - { role: ansible-roles/jenkins-docker-from-image }
    - { role: jenkins-config, tags: ["config"] }

- name: start nexus
  hosts: nexus
  roles:
    - { role: nexus }
