---
- name: setup docker, jdk on all hosts
  hosts: docker
  roles:
    - { role: ansible-roles/install-docker, docker_user: ubuntu }

- name: install and configure jenkins
  hosts: jenkins
  roles:
    - { role: ansible-roles/jenkins, become: true }
    - { role: jenkins-config, tags: ["config"] }
    - { role: tools }

- name: start nexus
  hosts: nexus
  roles:
    - { role: nexus }
