---
- fail: msg="JAVA_HOME is not set!"
  when: lookup('env','JAVA_HOME') == ''

- name: Print Machine Hostname
  debug: var=ansible_ssh_host

- set_fact:
    jenkins_url: "http://{{ansible_ssh_host}}:{{jenkins_port}}"

- include: cli.yml
- include: plugins.yml
- include: users.yml
